Preparation instructions added
fluttercandies/flutter_wechat_camera_picker pull request #8
Opened 2020-09-16 16:09 UTC by LaelLuo

2020-09-17 12:17 UTC, AlexV525 requested changes
LGTM modulo comments below.

2020-09-17 12:17 UTC, AlexV525 commented on README-ZH.md
> +在选择器唤起后，并且 `isAllowRecording` 为 `true`，点击拍摄按钮以拍照，长按拍摄按钮以录像。
Why two blank lines were added?

2020-09-17 12:17 UTC, AlexV525 commented on README.md
> +After called and the picker displayed, plus `isAllowRecording` is `true`, tap the shooting button to take a picture, long press the shooting button to record a video.
Same as above.

2020-09-17 15:35 UTC, LaelLuo commented on README-ZH.md
> +在选择器唤起后，并且 `isAllowRecording` 为 `true`，点击拍摄按钮以拍照，长按拍摄按钮以录像。
web ide issues

2020-09-18 01:35 UTC, AlexV525 approved these changes
Thanks for the first time contribution.

![image](https://user-images.githubusercontent.com/15884415/93545131-45371280-f992-11ea-9bb1-a65cb713462e.png)

2020-09-18 01:36 UTC, merged